### PR TITLE
Issue #460: Wallet connection improvements

### LINKED ISSUE #460: Wallet connection improvements
### Connection modal
- [ ] Missing metamask logo
- [ ] Change error text color to greyish `Error: Either Metamask....`
- [ ] No ability to disconnect/switch wallets
- [ ] Grey out  / disable other wallet options once one is active. Test UX around connecting and switching wallets.
- [ ] Add back "Disconnect" button for metamask, with same tooltip text as in #461 
- [ ] After successfully connecting, the modal should be hidden

image

### PR DESCRIPTION
**Pull request by jahabeebs**
Closes #460 

## Description
- [] Missing metamask logo

This only happens when MM is connected (because disconnect/try again is usually in the place of the logo but when connected there's nothing) and this is no longer an issue because we automatically close the wallet switching modal after connection and the user can't access that modal again if they're connected with MM

- [X] Change error text color to greyish `Error: Either Metamask....`

- [X] No ability to disconnect/switch wallets

The user is able to disconnect and connect to wallets -- see screenshots

- [] Grey out  / disable other wallet options once one is active. Test UX around connecting and switching wallets.

I can add this in but are we sure we want this? I forgot our reasoning behind this. It forces the user to press disconnect to connect to a different network, but if they just click the other network instead it connects them successfully or returns an error message (see screenshots)

- [] Add back "Disconnect" button for metamask, with same tooltip text as in #461 

The user will never be able to see "disconnect" or the tooltip for MM because the user can't access the modal switching screen. The user will be only be able to see a greyed out change button with the tooltip in #461  

- [X] After successfully connecting, the modal should be hidden

## Screenshots

Disconnect works from walletconnect

https://github.com/open-dollar/od-app/assets/47253537/9b57fa34-249c-46ef-90ce-ba84baf6ca90

Disconnect works from CB (but CB is special in that it triggers a refresh after disconnect)

https://github.com/open-dollar/od-app/assets/47253537/a58f7dac-b9d1-4d0d-8702-27dc47d0da6d

Modal closes automatically after connection (MM)

https://github.com/open-dollar/od-app/assets/47253537/09599843-c2b4-4806-a07c-35849902fdd8

Modal closes automatically after connection (wallet connect)

https://github.com/open-dollar/od-app/assets/47253537/9543447e-8d7e-4a6a-ab05-6c23ad7c67d8

Users can switch connection methods by clicking another one 

https://github.com/open-dollar/od-app/assets/47253537/fec491c5-5932-48b3-b4f8-67b93140244c

New greyish error text (this is our existing "tertiary" color in the app)

new error text

### CODE REVIEW

**Review by pi0neerpat — CHANGES_REQUESTED** [review]
Lets simplify this even more. Each wallet option should be a clear button (as in the other modals) with only three items- Icon, Name, status text (either "Connected", "Error", or empty). The item spacing and button height should never change.

- [ ] Move status text to the top. Either show "Chain: Arbitrum Sepolia", "Wrong Network", or the complete error text "Error: ....."
- [ ] When the selected wallet is in error state, its button status should be "Error". The error message should be shown at the top of the modal. Not sure how to handle the eager connection scenario. Can we suppress all errors from displaying until the user actually selects a wallet option?
- [ ] When a wallet is connected, its button status should be "Connected"
- [x] When a wallet is not connected, its button status should be empty

image

See Figma here: https://www.figma.com/file/R1tFeGSLIlSBu0HGpR45bL/OD-Mainnet?type=design&node-id=678-1010&mode=design&t=NerzxRRdfguDS5e3-0

**Comment by pi0neerpat** [comment]
After some additional thought, if you want to have a "Awaiting Connection..." status in the button, I think that is fine too.

**Comment by jahabeebs** [comment]
> Lets simplify this even more. Each wallet option should be a clear button (as in the other modals) with only three items- Icon, Name, status text (either "Connected", "Error", or empty). The item spacing and button height should never change.
> 
>     * [ ]  Move status text to the top. Either show "Chain: Arbitrum Sepolia", "Wrong Network", or the complete error text "Error: ....."
> 
>     * [ ]  When the selected wallet is in error state, its button status should be "Error". The error message should be shown at the top of the modal. Not sure how to handle the eager connection scenario. Can we suppress all errors from displaying until the user actually selects a wallet option?
> 
>     * [ ]  When a wallet is connected, its button status should be "Connected"
> 
>     * [ ]  When a wallet is not connected, its button status should be empty
> 
> 
> image
> 
> See Figma here: https://www.figma.com/file/R1tFeGSLIlSBu0HGpR45bL/OD-Mainnet?type=design&node-id=678-1010&mode=design&t=NerzxRRdfguDS5e3-0

@pi0neerpat 

Addressed all the changes except the wrong network thing -- when the user is on the wrong network they won't see the wallet modal, they'll see the wrong network banner. I couldn't find a way to be on the wrong network while having the modal open (the app doesn't know what network a user is on until they try to connect)

Desktop

desktop

Mobile

mobile

Chain at top, disconnect button, connected text under wallet

https://github.com/open-dollar/od-app/assets/47253537/0debdeea-02b8-44e2-a402-5b37d2d65873

Error message

error message

Awaiting connection text

https://github.com/open-dollar/od-app/assets/47253537/06402dbd-63d1-4ca7-8643-ed731d7b5fb6

**Review by pi0neerpat — CHANGES_REQUESTED** [review]
- [ ] The item spacing and button height should never change. Right now the button changes height when status text is shown
- [ ] The button should not change height when connected. Do not show "disconnect" option. The icon should remain visible. It should show "Connected" status.
- [ ] The placement of the wallet status text should reflect the design. Empty when not connected. Error when error. Chain details when connected. The height of the modal should not change.

image

**Comment by Seroxdesign** [comment]
- Still doesn't automatically close when connected
- Still prompts to add a network despite me having arbitrum in my wallet

Not sure if these are bugs you are working but I wanted to mention this

**Comment by jahabeebs** [comment]
> * [ ]  The item spacing and button height should never change. Right now the button changes height when status text is shown
> 
>     * [ ]  The button should not change height when connected. Do not show "disconnect" option. The icon should remain visible. It should show "Connected" status.
> 
>     * [ ]  The placement of the wallet status text should reflect the design. Empty when not connected. Error when error. Chain details when connected. The height of the modal should not change.
> 
> 
> image
> 
>     * [ ]  If possible we should not show the wallet connection modal if the wallet has already been connected. Eg. in this case only the "Initializing" should be shown
> 
> 
> Screen.Recording.2024-05-10.at.5.36.48.PM.mov

@pi0neerpat 

- [X] The item spacing and button height should never change. Right now the button changes height when status text is shown

I've added a mandatory height for the error messaging (up to two lines) and the chain information (one line). I'm not sure if you'll like it, it's a lot of space to always leave there. The design looks nicer than reality because 1) it's small white text and 2) it assumes there can be no error when a user is connected, which isn't the case. If a user is connected via walletconnect for example and tries to switch to coinbase wallet and there's an error then an error will be shown while a user's info is connected (which is why we need three lines of text for the height if you don't want to see any layout shift)

User connected, no errors

Screenshot 2024-05-13 at 4 08 38 PM

User connected with errors 

Screenshot 2024-05-13 at 4 09 41 PM

User not connected with errors

error text not connected

- [X] The button should not change height when connected. Do not show "disconnect" option. The icon should remain visible. It should show "Connected" status.

Added height changes (see above), eliminated disconnected text, icon is always visible (see above)

- [X] The placement of the wallet status text should reflect the design. Empty when not connected. Error when error. Chain details when connected. The height of the modal should not change.
 
Empty when not connected ✅ 
Chain details when connected (unless via network because this is misleading since none of the wallets will show as connected) ✅ 
Error when error ❌  

I know this is in the designs but the problem with this is a wallet error is just a string we get that's not connected to a particular connector instance. That means if a user is connected via walletconnect and there's an error it may be coming from metamask (if the user tries to connect to metamask and then rejects it or something else happens) so then it would replace the "Connected" text under walletconnect to be "Error" even though the user is indeed connected. 

- [X] If possible we should not show the wallet connection modal if the wallet has already been connected. Eg. in this case only the "Initializing" should be shown

This code got deleted somehow while I was merging with another branch. I fixed it and here's a demo:

https://github.com/open-dollar/od-app/assets/47253537/5c5b517f-3166-4551-a907-1e000ba6a3fb

**Review by pi0neerpat — CHANGES_REQUESTED** [review]
- Hide status "Awaiting connection" for wallet connect until the wallet is selected. Its unexpected for user's to see this when they first open the modal.
image
- Page, header contents should not shift or move when opening or closing the wallet modal

https://github.com/open-dollar/od-app/assets/35622595/3ca1fad0-466b-40ea-acbc-6185e253190e

> This code got deleted somehow while I was merging with another branch. I fixed it and here's a demo:

- Wallet modal now closes upon the first initial connection, but does not automatically close on future page-loads and connections.
> if a user is connected via walletconnect and there's an error it may be coming from metamask (if the user tries to connect to metamask and then rejects it or something else happens) so then it would replace the "Connected" text under walletconnect to be "Error" even though the user is indeed connected.
- Makes sense, lets completely remove the "Network: Arbitrum" feature then. 
- The error font size and color don't appear to match the designs. Also, should be left-aligned. The spacing for that section can be reduced if the font size is reduced, and the "Network" part removed. If a string doesn't fit in this space, it should be trimmed with "..."
image
image

**Comment by jahabeebs** [comment]
> * Hide status "Awaiting connection" for wallet connect until the wallet is selected. Its unexpected for user's to see this when they first open the modal.
>       image
> 
>     * Page, header contents should not shift or move when opening or closing the wallet modal
> 
> 
> Screen.Recording.2024-05-13.at.3.17.32.PM.mov
> 
> > This code got deleted somehow while I was merging with another branch. I fixed it and here's a demo:
> 
>     * Wallet modal now closes upon the first initial connection, but does not automatically close on future page-loads and connections.
> 
> 
> > if a user is connected via walletconnect and there's an error it may be coming from metamask (if the user tries to connect to metamask and then rejects it or something else happens) so then it would replace the "Connected" text under walletconnect to be "Error" even though the user is indeed connected.
> 
>     * Makes sense, lets completely remove the "Network: Arbitrum" feature then.
> 
>     * The error font size and color don't appear to match the designs. Also, should be left-aligned. The spacing for that section can be reduced if the font size is reduced, and the "Network" part removed. If a string doesn't fit in this space, it should be trimmed with "..." and a tooltip to view entire error.
>       image
>       image

- [X] Hide status "Awaiting connection" for wallet connect until the wallet is selected. Its unexpected for user's to see this when they first open the modal.

Added a new state variable that allows us to differentiate whether a user is just opening the connect wallet modal or if they're actively connecting and I filter the awaiting connection appropriately

https://github.com/open-dollar/od-app/assets/47253537/b49f7210-84e2-4409-a3d1-b9bd61fe2502

- [X] Page, header contents should not shift or move when opening or closing the wallet modal

This happens to every modal (not just the network modal) and on Chrome only but I found the cause was we were setting the overflow property of the body tag to be hidden or visible dynamically in the global styles so I fixed it by removing all the code that dynamically changes hidden or visible. I don't see this as a needed property because in our new design our modals are not overflowing the body tag

no layout shift chrome

https://github.com/open-dollar/od-app/assets/47253537/1572e564-c7ae-49e3-b922-57d3ebe1e1e0

- [X] Wallet modal now closes upon the first initial connection, but does not automatically close on future page-loads and connections.

Now if a user presses connect wallet and they're already connected it will automatically reconnect them and not show the wallet modal

https://github.com/open-dollar/od-app/assets/47253537/a6d785c9-57ae-47ba-9208-541cbb79b24f

- [X] Makes sense, lets completely remove the "Network: Arbitrum" feature then.

- [X] The error font size and color don't appear to match the designs. Also, should be left-aligned. The spacing for that section can be reduced if the font size is reduced, and the "Network" part removed. If a string doesn't fit in this space, it should be trimmed with "..." and a tooltip to view entire error.

I thought you wanted the error text grey but I changed it to match the designs instead. There's now space for a line of errors and when it overflows it'll show the ellipses and tooltip


test overflow

connected error

connected no error

**Review by pi0neerpat — APPROVED** [review]
Love it. Its so much better now!

**Pull request merged**
