### PR TITLE
Issue #606: Vaults explorer page

### LINKED ISSUE #606: Vaults explorer page
- [ ] Create a new "/explore" page
- [ ] Copy the code from marketplace to display all vaults in a table
- [ ] Pull data from the subgraph

### LINKED ISSUE #615: Explore: risk status column

### PR DESCRIPTION
**Pull request by jahabeebs**
closes #606 
closes #615 

## Description
- [X] Create a new "/explore" page
- [X] Copy the code from marketplace to display all vaults in a table
- [X] Pull data from the subgraph
- Updated yarn lock file which was failing

## Screenshots

Mobile

Screenshot 2024-07-03 at 10 06 11 PM

Desktop

Screenshot 2024-07-03 at 10 06 01 PM

Responsive 

https://github.com/open-dollar/od-app/assets/47253537/200d1256-0b62-4443-a8af-8a76f7fc096f

### CODE REVIEW

**Review by pi0neerpat — CHANGES_REQUESTED** [review]
- svg render issue
- add collateral and debt amounts

**Comment by jahabeebs** [comment]
> * svg render issue
> * add collateral and debt amounts

I made the following changes
- I found that the rendering issue only occurs when sorting by "ID" and "collateral". I tried to fix the rendering issue in a number of ways (triggering more re-renders with useEffect, annotating rows with unique ids, consolidating into one component, comparing with the marketplace logic) but there must be something going on with how tanstack is re-rendering the rows, because I wasn't able to get them to re-render correctly. I had to disable sorting by ID and collateral. The same issue is probably occurring on the marketplace route but there are so few listings either the rendering issue doesn't happen or we just don't have enough examples to see it happen
- I added collateral amount and debt amount and these sort correctly without rendering issues, though I had to do some string parsing


## Screenshots

https://github.com/open-dollar/od-app/assets/47253537/a5afc7f2-65c8-4ab6-8106-a3c787d4af92

**Review by pi0neerpat — CHANGES_REQUESTED** [review]

**Review by pi0neerpat — CHANGES_REQUESTED** [review]
Use internal link, not external link

**Comment by pi0neerpat** [comment]
image

ORDER:
ID, Image, Collateral Amount, Collateral, Debt

Collateral eg. "1,000 ARB"

**Comment by jahabeebs** [comment]
@pi0neerpat 

I made the following changes:
1) Passing the entire svg component into the table and trying to find other properties in info.row didn't help the svg rendering issue, I've kept sorting disabled for ID and collateral because I've been trying for a long time but still haven't found a workaround (though if someone search a collateral type in the search bar they can filter and it doesn't affect the SVG)

2) I re-ordered the columns to ID, Image, Collateral Amount, Collateral, Debt
3) View button is now an internal link

Re-ordered columns

Screenshot 2024-07-08 at 5 51 38 PM


Re-ordered columns

Screenshot 2024-07-08 at 5 51 49 PM

Responsive

https://github.com/open-dollar/od-app/assets/47253537/4644c541-c506-49c1-a7a6-33d46be227d9

**Review by pi0neerpat — CHANGES_REQUESTED** [review]
Continue troubleshooting per discussion this morning

**Comment by jahabeebs** [comment]
> Continue troubleshooting per discussion this morning

@pi0neerpat 

I did the following today:
1) Added risk status column (#615) which we can sort by
2) I found our cratio calculation was incorrect sometimes, as we weren't filtering commas from numbers we were parsing and those numbers became NaN. Also, we weren't handling the differences between infinity and 0 correctly (since if a vault still has collateral it will be considered to have an infinity collateral ratio) and I fixed that. The color issue is still a problem and I'll have to debug more with a local svg package

**Review by pi0neerpat — APPROVED** [review]

**Pull request merged**
