### PR TITLE
Earn page react-loading-skeleton

### LINKED ISSUE #494: Earn page react-loading-skeleton
Depends on #486 

Add react-loading-skeleton for the list rows, instead of the loading spinner

Image

### PR DESCRIPTION
**Pull request by alekseevaiana**
closes #494 

Screenshot 2024-06-28 at 9 43 45 AM

https://github.com/open-dollar/od-app/assets/36742189/07311d58-5707-487d-afd6-3c48f1cd2c1d

### CODE REVIEW

**Comment by pi0neerpat** [comment]
Build is failing due to lockfile not being committed to git

**Comment by pi0neerpat** [comment]
Colors to try: #89B3FB #2871FD

**Review by pi0neerpat — CHANGES_REQUESTED** [review]
- 3 containers
- same height as earn container

**Comment by alekseevaiana** [comment]
Updated it closer to block size. But didn't ask earlier what if we have multiple pools, is it ok to show skeleton just for the first block? Otherwise I think we should change the logic of fetching pools.

https://github.com/open-dollar/od-app/assets/36742189/9b712ad0-b879-41d5-b76d-18a64e8d7c22

**Comment by pi0neerpat** [comment]
We will have multiple items here. The size of each box and the spacing between them should be the same

**Comment by alekseevaiana** [comment]
> We will have multiple items here. The size of each box and the spacing between them should be the same. Right now it looks like they are too close

Do you mean box as Skeleton line? Does each Skeleton line should "close" one pool item? Or three Skeleton lines "closes" all pool items, so I need to make space (between lines) the same as each Skeleton's line height?

**Comment by alekseevaiana** [comment]
So I made one Skeleton as a one pool, and while it is loading we are showing three blocks

https://github.com/open-dollar/od-app/assets/36742189/adfd02c0-7265-47b0-89d3-a89152fd1219

**Review by pi0neerpat — APPROVED** [review]

**Pull request merged**
