### PR TITLE
Issue # 547 QA Bridge page

### LINKED ISSUE #547: Bridge: page
- [x] Trim all assets to 4 decimals
- [x] Table of assets should always be shown. 
- [x] Add the loading spinner for asset amounts
 
image

- [x] Add light grey divider between rows in the table
- [x] There is a margin/gap between rows which is not click-able. This should be removed so the entire row height is clickable

image

- [ ] Add network icons for each item

image

- [ ] Add asset icons for each item (use existing icons)

image

- [x] Lets make the network selection as tabs, rather than a dropdown. We can use the same tabs as the vault page 
image

image

- [x] CreateVault and ModifyVault

Send the user to the bridge page instead of using a modal

### PR DESCRIPTION
**Pull request by alekseevaiana**
closes #547

## Issues and questions
- Table of assets is always shown now and the are the same for every network. Please let me know if it is wrong
- I added loader component for balances but not sure that my logic is right. Maybe I should remove it if user didn't connect a wallet? 
- Also I think I should change the logic showing and loading balances. Right now when I switch between tabs sometimes it is crashing
- Couldn't find icons for network (Mainnet: ETH (only this I have), Optimism, Polygon, Base)

### Not connected
Screenshot 2024-06-03 at 2 20 21 PM
### Connected
Screenshot 2024-06-03 at 2 20 34 PM

### CODE REVIEW

**Review by pi0neerpat — CHANGES_REQUESTED** [review]
- Remove WETH
- Show no values when wallet not connected
- When switching network, all values should switch to loading state
- Create a list of all failed requests (network, address, token name)
- Add network icons

**Comment by alekseevaiana** [comment]
### Mobile
Screenshot 2024-06-04 at 4 25 38 PM

**Review by pi0neerpat — CHANGES_REQUESTED** [review]
- [ ] Data should persist when switching tabs
- [ ] Remove margin between columns on mobile tabs
- [ ] Work with Jacob to fix the broken tokens

**Comment by alekseevaiana** [comment]
Screenshot 2024-06-06 at 12 17 38 PM
Screenshot 2024-06-06 at 12 17 24 PM

**Pull request merged**
