### PR TITLE
Issue #534 Bolts: mobile cleanup #2 

### LINKED ISSUE #534: Bolts: mobile cleanup #2
Update mobile view to match the new designs designs https://www.figma.com/design/EkcMRZhPra8NezYKt4zn7s/OD-testnet-app?node-id=1292-1224&t=Am6qq0ISmxkYq41d-0

Depends on #524, #532

- [ ] move button to below description text
image
- [ ] Ensure button text stays within buttons
image

### PR DESCRIPTION
**Pull request by alekseevaiana**
closes #534 

- cleaned up
- because of flex container images and button were squeezed, so I made it flex-wrap

Screenshot 2024-06-10 at 11 03 11 AM

### CODE REVIEW

**Review by pi0neerpat — CHANGES_REQUESTED** [review]
- [ ] Content order and button width should match mobile designs
image
- [x] Icons should always stay together, and not be separated by lines
image

- [ ] Token icon should be updated everywhere. Please update here and check if the old one is still being used anywhere else
image

**Comment by alekseevaiana** [comment]
Which way is better? I think about rm wallet image and put token instead (2)
### 1
Screenshot 2024-06-11 at 12 23 32 PM

### 2
Screenshot 2024-06-11 at 12 25 15 PM

**Comment by alekseevaiana** [comment]
### For mobile
Screenshot 2024-06-11 at 12 44 16 PM

**Comment by alekseevaiana** [comment]
Screenshot 2024-06-11 at 12 56 05 PM
Screenshot 2024-06-11 at 12 56 12 PM

**Review by pi0neerpat — CHANGES_REQUESTED** [review]
- [x] Tokens should not go on a new line. Eg. the title here should only be two lines. 
image
- [ ] Wallet dropdown on desktop extends beyond the page content. It also makes the page wider, which adds a scrollbar. This is not intended behaviour, since all page content should be within the page width
image
- [ ] I like option 1, since it makes it clear this is your wallet information

**Comment by alekseevaiana** [comment]
For icons:
I inlined them, but icons has different sizes, so I was able to put it only on a middle line

Screenshot 2024-06-11 at 8 46 06 PM

### Just an example what happened if I try to put it on the bottom line
Screenshot 2024-06-11 at 8 49 39 PM

**Review by pi0neerpat — APPROVED** [review]

**Pull request merged**
