### PR TITLE
Issue #497. NFV owner bug.

### LINKED ISSUE #497: NFV owner bug
Depends on #555 

Owner of the NFV should be pulled from nfv data, not the user's wallet.

Ask Jacob for help finding the data

### PR DESCRIPTION
**Pull request by alekseevaiana**
closes #497 

I made changes, but there is a bug with isOwner prop: it could show me that I am the owner of wallet even if I am not

### Disconnected
Screenshot 2024-06-14 at 10 55 03 AM

### Connected
Screenshot 2024-06-14 at 10 55 11 AM

### CODE REVIEW

**Review by pi0neerpat — CHANGES_REQUESTED** [review]
See discussion in discord re: owner address

**Comment by Seroxdesign** [comment]
## How to move this forward:

- We need to make sure the address is fetched internally
- It needs to be the Owner of the vault, not the currently connected account

**Review by pi0neerpat — CHANGES_REQUESTED** [review]
Always show owner

**Comment by alekseevaiana** [comment]
Screenshot 2024-06-17 at 9 32 08 AM

### Link to arbiscan

https://arbiscan.io/address/0x0005AFE00fF7E7FF83667bFe4F2996720BAf0B36#readContract

**Review by pi0neerpat — APPROVED** [review]

**Pull request merged**
