### PR TITLE
Fetch nitro pools state

### PR DESCRIPTION
**Pull request by Seroxdesign**
closes: #449

### CODE REVIEW

**Comment by pi0neerpat** [comment]
Rebased to dev, since epic/web-redesign was merged

**Review by pi0neerpat — CHANGES_REQUESTED** [review]
image

- Format numbers with commas for both TVL and APY
- Rename "APY" to "APR"
-  Status should not be active (starts Sunday 10am est)

**Comment by Seroxdesign** [comment]
Use this to test the math

https://app.camelot.exchange/nitro/0x626a551E910EcCA62e61DCeB37e3726C7d423185

**Review by pi0neerpat — CHANGES_REQUESTED** [review]
image

- [ ] TVL and APR do not match whats on the nitro pool https://app.camelot.exchange/nitro/0x626a551E910EcCA62e61DCeB37e3726C7d423185. I think you are calculating the TVL using the swap pool rather than the Nitro pool.

image

- [x] For APY- Camelot is including swap fees in that calculation, which makes things very complicated. Rather than confuse users with inconsistent values, lets just scrape that data directly from their nitro page.

**Pull request merged**
